USE [master]
GO

/****** Object:  Database [Suscripciones]    Script Date: 22/3/2021 22:37:11 ******/
CREATE DATABASE [Suscripciones]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Suscripciones', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Suscripciones.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Suscripciones_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Suscripciones_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Suscripciones].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Suscripciones] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Suscripciones] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Suscripciones] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Suscripciones] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Suscripciones] SET ARITHABORT OFF 
GO

ALTER DATABASE [Suscripciones] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Suscripciones] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Suscripciones] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Suscripciones] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Suscripciones] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Suscripciones] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Suscripciones] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Suscripciones] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Suscripciones] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Suscripciones] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Suscripciones] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Suscripciones] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Suscripciones] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Suscripciones] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Suscripciones] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Suscripciones] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Suscripciones] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Suscripciones] SET RECOVERY FULL 
GO

ALTER DATABASE [Suscripciones] SET  MULTI_USER 
GO

ALTER DATABASE [Suscripciones] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Suscripciones] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Suscripciones] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Suscripciones] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Suscripciones] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Suscripciones] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Suscripciones] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Suscripciones] SET  READ_WRITE 
GO

